FROM hypriot/rpi-node:latest

MAINTAINER Björn Kjeholt <dev@kjeholt.se>

ARG DOCKER_IMAGE_NAME
ARG DOCKER_IMAGE_TAG

ENV DOCKER_BASE_IMAGE_NAME na
ENV DOCKER_BASE_IMAGE_TAG na

ENV DOCKER_IMAGE_NAME ${DOCKER_IMAGE_NAME:-UnknownName}
ENV DOCKER_IMAGE_TAG ${DOCKER_IMAGE_TAG:-UnknownRevision}

RUN apt-get update && \
    apt-get install -y vim \
                       ow-shell \
                       owserver && \
    rm -rf /var/lib/apt/lists*

RUN mkdir -p /usr/src/app && \
    mkdir -p /usr/src/app/js && \
    mkdir -p /usr/src/app/script
    
WORKDIR /usr/src/app

# Install app dependencies
COPY package.json /usr/src/app/package-original.json
RUN \
    sed 's/TestWrapper/js\/main/g' package-original.json > package.json && \
    rm -rf node_modules nbproject && \
    echo "----------------" && \
    ls -laR && \
    echo "----------------" && \
    cat package.json && \
    echo "----------------"

RUN npm install

# Bundle app source
COPY js /usr/src/app/js
COPY Scripts /usr/src/app/script

RUN chmod 755 /usr/src/app/script/* && \
    chmod 755 /usr/src/app/*

# RUN echo "------------------------" && \
#     ls -lR /usr/src/app/script/ && \
#     echo "------------------------"

COPY Config/owfs.conf /etc/owfs.conf

VOLUME /mnt/1wire
# EXPOSE 4304


CMD script/execute.sh

